### ISSUE TITLE
Add options sidebar

### ISSUE THREAD

**Issue by zaataylor** [zaataylor/pomospendo#4]
Add an options sidebar containing:
- [ ] More information about the project (#3)
- [ ] Dark/light mode toggle settings (#9)
- [ ] Settings to reset the Pomodoro counter (#10)
- [ ] Optional text field descriptions of the current activity ([suggested](https://news.ycombinator.com/item?id=26964456) by huttie) (#11)
- [ ] Toggleable Pomodoro "debt" (#12)
- [ ] Sound options selection (#13)

Potentially also add:
- [ ] Alternative alert mechanism: current idea around this would be simply changing the title of the tab in rapid succession until a user refocuses the tab. This might be a bit annoying though...🤔
